version: "3"
services:
  db:
    image: reg.hthl-tech.com/library/postgres:10-alpine
    container_name: hthl_pms_db
    ports:
      - 15432:5432
    volumes: 
      - ./db/data:/var/lib/postgresql/data
    environment
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=root
      - POSTGRES_DB=db