version: "3"
services:
  db:
    image: reg.hthl-tech.com/library/postgres:10-alpine
    container_name: db
    ports:
      - 15432:5432
    volumes: 
      - ~/hthl.pms/db/data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=root
      - POSTGRES_DB=db


# docker run -it -d --name db -v /hthl.pms/db/data:/var/lib/postgresql/data -p 5432:5432 -e PGDATA=/var/lib/postgresql/data  -e POSTGRES_PASSWORD=123456 -e POSTGRES_USER=root -e POSTGRES_DB=db postgres:10-alpine